### ISSUE TITLE
Start slider from another position.

### ISSUE THREAD

**Issue by RokasAug** [eliotfowler/EFCircularSlider#35]
How could I change slider starting point? For example from west instead north?

**Comment by RokasAug** [comment]
@fatuhoku 
@hodgesmr 
@eliotfowler 
@kenthumphries 
@ciotto

**Comment by eliotfowler** [comment]
In `-viewDidLoad` of your UIViewController that is responsible for controlling the slider, set the currentValue like this:

circularSlider.currentValue = 270;
